Documentation
redhat-performance/speccpu2017-wrapper pull request #13
Opened 2023-07-17 18:25 UTC by dvalinrh

2023-07-17 19:15 UTC, kdvalin requested changes

2023-07-17 19:15 UTC, kdvalin commented on README.md
> +[root@hawkeye ~]# git clone https://github.com/redhat-performance/speecpu2017-wrapper
```suggestion
[root@hawkeye ~]# git clone https://github.com/redhat-performance/specpu2017-wrapper
```

2023-07-18 09:10 UTC, dvalinrh commented on README.md
> +[root@hawkeye ~]# git clone https://github.com/redhat-performance/speecpu2017-wrapper
Thank you.

2023-07-18 13:22 UTC, kdvalin approved these changes
LGTM

2023-07-18 13:25 UTC, merged